version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - ./static:/code/static
      - ./staticfiles:/code/staticfiles
      - ./media:/code/media
      
    ports:
      - "8081:8000"
    environment:

        - "DJANGO_SECRET_KEY=${DOCKER_COMPOSE_DJANGO_SECRET_KEY}"
        - "DJANGO_EMAIL=${DOCKER_COMPOSE_DJANGO_EMAIL}"
        - "DJANGO_DEBUG=${DOCKER_COMPOSE_DJANGO_DEBUG}"
        - DJANGO_ADMIN_URL=${DOCKER_COMPOSE_DJANGO_ADMIN_URL} 
        - DJANGO_ALLOWED_HOSTS=${DOCKER_COMPOSE_DJANGO_ALLOWED_HOSTS}
        
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: ${DOCKER_COMPOSE_DJANGO_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DOCKER_COMPOSE_DJANGO_POSTGRES_PASSWORD}
      POSTGRES_DB: ${DOCKER_COMPOSE_DJANGO_POSTGRES_DB}
