# Generated by Django 5.1.5 on 2025-02-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezomeh', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='Address',
            field=models.TextField(verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='home',
            name='email',
            field=models.EmailField(max_length=155, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='home',
            name='expertise',
            field=models.CharField(max_length=155, verbose_name='expertise'),
        ),
        migrations.AlterField(
            model_name='home',
            name='freelance_status',
            field=models.CharField(choices=[('available', 'Available'), ('not_available', 'Not Available'), ('busy', 'Busy')], default='not_available', max_length=15, verbose_name='freelance_status'),
        ),
        migrations.AlterField(
            model_name='home',
            name='name',
            field=models.CharField(max_length=155, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='home',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='phone_number'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='category',
            field=models.CharField(choices=[('personal', 'Personal'), ('store', 'Store'), ('python', 'Python')], max_length=20),
        ),
    ]
