# Generated by Django 5.1.6 on 2025-02-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezomeh', '0003_alter_home_address_alter_home_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
