# Generated by Django 5.1.6 on 2025-02-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezomeh', '0004_portfolio_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='github_link_django',
            field=models.URLField(blank=True, null=True),
        ),
    ]
