# Generated by Django 5.2 on 2025-04-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezomeh', '0005_portfolio_github_link_django'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='description',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='short_description',
            new_name='short_description_en',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='technology',
            new_name='technology_en',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='title',
            new_name='technology_fa',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='title_en',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='description',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='technology',
            new_name='technology_en',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='title',
            new_name='title_fa',
        ),
        migrations.RenameField(
            model_name='rezomeh',
            old_name='short_description',
            new_name='short_description_en',
        ),
        migrations.RenameField(
            model_name='rezomeh',
            old_name='title',
            new_name='title_en',
        ),
        migrations.AddField(
            model_name='blog',
            name='description_fa',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='short_description_fa',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_en',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='title_fa',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='title_fa',
            field=models.CharField(default='', max_length=155),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='description_fa',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='technology_fa',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='title_en',
            field=models.CharField(default=' ', max_length=155),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rezomeh',
            name='short_description_fa',
            field=models.TextField(default='exit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rezomeh',
            name='title_fa',
            field=models.CharField(default='', max_length=155),
            preserve_default=False,
        ),
    ]
